package de.bytesoftware.keys.gateway.entities;

public enum Error
{

	DATA_OBJECT_IS_MISSING, USER_ALLREADY_EXISTS, MISSING_SESSION_ID, USERNAME_MAY_NOT_BE_EMPTY, PASSWORD_MAY_NOT_BE_EMPTY, USERNAME_OR_PASSWORD_FAILURE, USER_NOT_FOUND, USER_NOT_LOGGED_IN, INVALID_ACCOUNT_DATA, NAME_IS_REQUIRED, ACCOUNT_NOT_FOUND, PLAN_SCHEDULE_INVALID, INVALID_DATA, NO_TRANSACTIONS_FOUND_FOR_THIS_ACCOUNT, CATEGORY_NOT_FOUND, NO_TRANSACTIONS_FOUND_FOR_THIS_CATEGORY

}
